### ISSUE TITLE
Components should not be selected only by name

### ISSUE THREAD

**Issue by janhaa** [retejs/lifecycle-plugin#2]
Currently, the methods are triggered by selecting a node through its name. But if you have multiple instances of one type of node, the methods are called for all of these, which is unexpected behaviour.

Talking about this:
`editor.getComponent(input.node.name)`

Might submit a PR soon.

**Comment by Ni55aN** [comment]
The `name` in a node and component is a human-friendly identifier

**Comment by Ni55aN** [comment]
>  But if you have multiple instances of one type of node, the methods are called for all of these, which is unexpected behaviour.

https://github.com/retejs/lifecycle-plugin/blob/51493d05cd934b064271ad3deab093b8085ff162/src/index.js#L23-L24

getComponent is looking for a Component instance, not Node

**Comment by Ni55aN** [comment]
Can you share an example on codepen/jsfiddle?

**Comment by janhaa** [comment]
Hi, I don't have the time to prepare one right now. Take this example code:

```
export default class StreamLatestComponent extends Rete.Component {
  constructor() {
    super("StreamLatest");
  }
  onconnect(io) {
  }
}
```

But I have two instances of StreamLatest like this:

![image](https://user-images.githubusercontent.com/1587235/67130084-9b3e8b80-f200-11e9-8a25-693c1d40b30a.png)

When I connect something to **one** of the two components, the `onconnect` method still gets called two times, since `onconnect` is invoked via `editor.getComponent(input.node.name).onconnect(input)`. From my understanding it should look for individiual nodes, something like this (probably not 100% right):
```
editor.on('connectioncreate', ({ input, output }) => {
    let inputNode = editor.nodes.find(node => node.id == input.node.id);
    let outputNode = editor.nodes.find(node => node.id == output.node.id);
    return inputNode.onconnect(input) === true && outputNode.onconnect(output) === true;
});
```

Get my point? Or am I misunderstanding something?

My current workaround is to not use the lifecycle-plugin, but to do this in the component:
```
builder(node) {
    this.editor.on("connectioncreate", ({ input, output }) => {
        if(input.node.id !== node.id && output.node.id !== node.id)
            return;

        /* rest of code */
    });
}
```

All the best!

**Comment by Ni55aN** [comment]
>  onconnect method still gets called two times

This is the expected behavior, since `onconnect` is called for Input and Output of two nodes you connect

**Comment by janhaa** [comment]
Yeah I see, I re-thought this and see how your design was intended now. :) Cheers!
